### PR TITLE
Changed Admin app to single tenant

### PR DESCRIPTION
**Pull request by neelavarshad**
Updated admin app configs 
Changed variable name for checking if app regs are provided

### CODE REVIEW

**Comment by santhoshb-msft** [comment]
Hi @neelavarshad lets talk more on Monday before we merge this.

**Comment by neelavarshad** [comment]
Fixes comments from #698 
Fixes #716 to explicitly make fulfillment app reg single tenant

**Review by bkhabazan — APPROVED** [review]
Test complete, all changes are approved.

**Review by bkhabazan — APPROVED** [review]

**Comment by bkhabazan** [comment]
All tests passed and approved

**Comment by neelavarshad** [comment]
@santhoshb-msft I pushed the default set to false. You can validate on this now.

**Comment by santhoshb-msft** [comment]
Hi @neelavarshad I tried to install this branch twice but keeps failing , can you please rerun on your side again

image

**Comment by neelavarshad** [comment]
@bkhabazan  Did you see anything like what Santhosh is encountering?

**Comment by bkhabazan** [comment]
I did not see any error messages when running the code. I was able to deploy successfully.

**Comment by santhoshb-msft** [comment]
I just ran again and same issue, lets connect internally to if the script is missing anything

**Comment by neelavarshad** [comment]
@santhoshb-msft Please try again with the latest changes I added. Thanks!

**Comment by santhoshb-msft** [comment]
Hi @neelavarshad just checking if the multiple url display issue is fixed?

**Comment by neelavarshad** [comment]
@santhoshb-msft  This is fixed now

**Comment by santhoshb-msft** [comment]
@neelavarshad have you seen the below by any chance?

image

**Comment by neelavarshad** [comment]
I ran through several tests last week and didn't see anything with MSI. What point of the script is this coming up on? Is it only on my branch you're seeing this?

**Comment by santhoshb-msft** [comment]
> I ran through several tests last week and didn't see anything with MSI. What point of the script is this coming up on? Is it only on my branch you're seeing this?

Yes @neelavarshad, just running your branch
git clone https://github.com/neelavarshad/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK.git -b single-tenant-admin; `
Can you run like on a clean az cloud shell?

**Comment by neelavarshad** [comment]
@santhoshb-msft 
I just ran on a clean cloudshell and didn't see what you're seeing. It ran the update firewall commands and directly went to cleanup without any errors. Can you share the full error via DM? I'll look into it if you'd like.
image

**Review by santhoshb-msft — APPROVED** [review]
1. Tested with new install
2. Validate all three-app registration and their redirect uris
3. Validated app service setting for both admin portal and customer portal
4. Switched single to muliti tenant . for future we might need docs on how to swtich, 3 steps, enble app service flag, switch app reg and add user to knownusers
5.

**Pull request merged**
