### PR TITLE
Fixed spelling errors in completion steps

### PR DESCRIPTION
**Pull request by fthorntonai**
Write-host "✅ If the installation completed without error complete the following checklist:"

### CODE REVIEW

**Review by santhoshb-msft — APPROVED** [review]
typos fixes approved

**Comment by santhoshb-msft** [comment]
@fthorntonai can you fix the conflicts please?

**Comment by fthorntonai** [comment]
marking WIP

**Comment by fthorntonai** [comment]
@santhoshb-msft Done. Can you validate that I included the correct line after the spelling error change. 

Regards,
FT

**Comment by santhoshb-msft** [comment]
As discussed with @fthorntonai, closing this PR. Please raise a new one as needed.

**Pull request closed without merging**
