### PR TITLE
fix email logo

### PR DESCRIPTION
**Pull request by msalemcode**
Replace the email log with updating live link

### CODE REVIEW

**Comment by alexdrenea** [comment]
Looks good to me! 
But wanted to make sure it's understood this will only work for new deployments of the accelerator. 
For anyone who's deployed it before this change, they would need to go and manually make the changes in the templates (though the db or admin UI)

**Comment by msalemcode** [comment]
> 

@alexdrenea This is correct, it is will be for future deployments. Existing deployment will need manual fix

**Review by code4clouds — COMMENTED** [review]
Why are these files not local on the src report?

**Review by code4clouds — CHANGES_REQUESTED** [review]
Please change the logo to be the logo served by the landing page (https://<prefix>-portal.azurewebsites.net/contoso-sales.png).

**Review by code4clouds — APPROVED** [review]

**Pull request merged**
