### PR TITLE
AZ CLI based deployment script.

### PR DESCRIPTION
**Pull request by alexdrenea**
Provides an updated script to deploy the entire solution with one single Az-Cli based script

The script can be ran from cloud shell so does not require the end-user to deploy / install anything on their local machine.

Notable changes from the original deploy.ps1 script:

- Fully AZ-CLI based, no dependencies on AzureRM
- Simplified mandatory parameter list with most of the parameters having defaults that are inferred from the chosen WebAppNamePrefix parameter
- SQL user / pass are auto-generated and discarded after the script runs for added security
- Added KeyVault integration with all secrets (SQL and AppRegistration secret) stored and referenced from a KeyVault for better security

### CODE REVIEW

**Comment by dstarr** [comment]
We very much appreciate the work that has gone into this and we really like some of the choices you are making (KV, for example) in the install. We are hoping to use an all PowerShell installer script. Jumping back and forth between az CLI and PS within the same script can be very confusing for later maintenance.

A simple example is using `az command ...` followed by a PS `Write-Host` command. Another might be using curl instead of Invoke-RestMethod.

We're all-in on PowerShell and migrating that direction. Further, we want to use ARM for resource creation as much as possible as it is the standard template format for creating resources in Azure. Yes, they can be scripted, but that tends to lead to higher maintenance costs for the scripting.

Anxious to hear your thoughts.

**Comment by alexdrenea** [comment]
Thank you David for your comments and for the opportunity to continue the conversation...

I would love to chat about the reasons of introducing Az Cli in the scripting even if it's not PowerShell native. 
Also would love to brainstorm the merits of replacing the ARM template with a pure CLI option.

Either way, my ultimate goal is to provide options for the end-users regardless of their preferences / skills are.

That being said, I'm open and willing to update the current deploy script to include some of the "goodies" from this update - open for discussion but I am thinking mostly of KeyVault, deploying without the temp storage account and simplified input parameter list.

**Comment by dstarr** [comment]
Alex,

Now that we've had more conversations via chat, do you want to keep this PR open or work with a different one? It's been open for about 6 weeks, so it's likely behind a bit. Thgouhts?

**Comment by alexdrenea** [comment]
Hey, sorry for the delay! Holidays and back to work have been busy times :)

I am working on a separate PR based on the conversations we've had - i.e. ARM + PowerShell. 
I still think there's value in a pure Az CLI script for customers who prefer CLI to ARM but if the team does not want this, happy to close the PR.

**Comment by dstarr** [comment]
Thank you for acknowledging the goals of the project.

Please do.

**Pull request closed without merging**
