### PR TITLE
Refresh plan name

### LINKED ISSUE #353: Wrong SubscriptionStatus in Subscription Details page
**Describe the bug**
In Admin Portal, Subscription Details page displays wrong Status (it is hooked up to SaaSSubscriptionStatus property instead of SubscriptionStatus so it always shows PendingFulfullmentStart

**To Reproduce**
1. Go to Admin Portal
2. Click on 'Subscription Details"

**Expected behavior**
Show correct Status as presented in the subscriptions table.

### PR DESCRIPTION
**Pull request by alexdrenea**
### Logic:

- when changing plan, ensure we update the database with the new plan for the offer (and log)
- when fetching subscription list, ensure we refresh plan name, quantity or status and log

### UI:
- change plan / change quantity are long running operations (30s-60s). Disable button and show spinner on page while operation is in progress for both change plan and change quantity modals both in admin portal and customer portal
 
image

Addresses #345 , #350
Also fixes #353 , #354

### CODE REVIEW

**Comment by santhoshb-msft** [comment]
@alexdrenea I believe this should always be handled by the response on the webhook. I think we can do it here too but webhook is generally the better place to handle this update.

**Comment by alexdrenea** [comment]
> @alexdrenea I believe this should always be handled by the response on the webhook. I think we can do it here too but webhook is generally the better place to handle this update.

I like this! Lemme look into it!
Meanwhile, if you get a moment to check the rest of the PR that would be great!

**Comment by alexdrenea** [comment]
> @alexdrenea I believe this should always be handled by the response on the webhook. I think we can do it here too but webhook is generally the better place to handle this update.

@santhoshb-msft I verified, and it looks like the change is applied correctly in the webhook as you mentioned. I could have sworn I saw an issue where the plan was not updated. But I retried it both from customer portal and admin portal and it works as expected.

And in any case, if there is any kind of transient problem, the "Fetch All Subscription" button will now force refresh everything.

Thank you. I reverted all the changes in HomeController related to changing the plan there!

**Comment by santhoshb-msft** [comment]
@dstarr this might be fixing #219 as well

**Review by dstarr — COMMENTED** [review]
This is not working for me at present. The UX looks like it runs properly, but the plan is not changed in the Subscriptions table.

The plan IS changed however when viewed from the customer's view in the Azure portal.

**Review by dstarr — CHANGES_REQUESTED** [review]
The changes to **FetchAllSubscriptions** are not synching Plans or Offers. The call completes with a 200, but only the Subscriptions table is populated.

**Pull request closed without merging**
