### PR TITLE
Verify webhook notification

### PR DESCRIPTION
**Pull request by caseywatson**
This PR includes a recommended webhook verification fix. Needs to be tested with an actual live offer.

### CODE REVIEW

**Comment by code4clouds** [comment]
We looked at the code, but were not able to test due to an issue in the back end.  In the meantime @caseywatson, would you mind clean out the comments/questions in the code?

**Comment by caseywatson** [comment]
Will do, @code4clouds.

**Comment by caseywatson** [comment]
I left in comments that I thought were still relevant. Let me know if you'd like to make any further changes. Please keep me in the loop re: testing... happy to collaborate there as well.

**Comment by code4clouds** [comment]
@caseywatson  - Would you mind updating your code one more time?  We no longer need the exception been thrown as we have a new default to show the users there is an unknown action.

**Comment by code4clouds** [comment]
This will followed on PR #306

**Pull request closed without merging**
