### PR TITLE
Added in-memory database for local testing

### PR DESCRIPTION
**Pull request by scottperham**
Added EF InMemory database provider for local testing without SQL dependency.

### CODE REVIEW

**Review by santhoshb-msft — COMMENTED** [review]
@scottperham this is great but just a couple of thoughts.
1. can we add a warning on the pages , if the in-memory db is used please
2. is there a way we can only have this enabled in localhost and/or debug mode

Trying to avoid the risk of someone accidentally using this and realizing later. Please let me know what you think

**Comment by scottperham** [comment]
@santhoshb-msft I have added the following message to the top of the pages for both the customer site and admin site when the in-memory database provider is being used...

image

**Comment by santhoshb-msft** [comment]
Hi @scottperham could you please help resolve the conflicts.

**Comment by santhoshb-msft** [comment]
@scottperham I think it would help if this is driven by the appsetting. Developermode appsetting and no connectionstring then enable the inmemory db please?

**Comment by santhoshb-msft** [comment]
@scottperham please let me know if we can do that above and resolve some conflicts.

**Comment by santhoshb-msft** [comment]
@scottperham please let me know if you can fix as per comments

**Comment by santhoshb-msft** [comment]
Closing this as no response. Please feel to reopen once the conflicts are resolved with the above feedback.

**Pull request closed without merging**
