### PR TITLE
Feature/Rewrite tests with xUnit

### LINKED ISSUE #405: Move tests to xUnit
**Please describe.**
Move from MS Test unit testing framework to xUnit

**Additional context**
This is a move to simplify the tests that we create for the project. xUnit is faster with less complex setup and teardowns than MS Test.

Agreed with Patrick

### PR DESCRIPTION
**Pull request by kek-Sec**
I believe further improvements can be done on the tests but I wanted to keep this just transition related.

closes #405

### CODE REVIEW

**Comment by kek-Sec** [comment]
@microsoft-github-policy-service agree

**Comment by dstarr** [comment]
If you fix the conflicts I'll test this PR

**Review by dstarr — CHANGES_REQUESTED** [review]
Please remove package references to MS Test framework from the project file.

**Comment by dstarr** [comment]
Actually, @kek-Sec - We just had an internal discussion and have come to agreement that we'll grow out our tests from here using MSTest. Our reason is that it has better support for integration tests, which we'll be using in addition to unit tests and we want to keep only one test framework in the project.

Thank you for your support and I hope you'll pull another item to enhance the project.

**Pull request closed without merging**
