### PR TITLE
fixed modal ui related bugs

### PR DESCRIPTION
**Pull request by santhoshb-msft**
Fixed bugs #334 and #333

### CODE REVIEW

**Comment by santhoshb-msft** [comment]
@msalem  this seems to cause #333 
https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/pull/232/files#diff-cec1e21ac6f154342c773b739df56c4f7e2bdf4b1cec06961e2388da864b6406

**Comment by alexdrenea** [comment]
I think this is a pretty big one. If at all possible, it should be prioritized and merged into v6 as a hotfix. 

I already had to work with a partner that needed to change their customer plan and it was a bit weird to show them that they have to inspect the page and manually delete the modal div in order to change the plan.

**Review by alexdrenea — APPROVED** [review]

**Comment by alexdrenea** [comment]
@santhoshb-msft reviewed, all look good but you still need someone from the team to approve before you can merge

**Comment by santhoshb-msft** [comment]
Thank you for approving this @alexdrenea !
Looking forward to @msalemcode approving before I can merge it.

**Review by msalemcode — APPROVED** [review]

**Pull request merged**
