### PR TITLE
Update Installation-Instructions.md

### PR DESCRIPTION
**Pull request by santhoshb-msft**
This pull request includes changes to the `docs/Installation-Instructions.md` file to update the installation instructions for .NET and related tools. The most important change is the downgrade of the .NET version and the `dotnet-ef` tool version.

Key changes:

* [`docs/Installation-Instructions.md`](diffhunk://#diff-7fde675f58b920435dbbb78464bb397a57debb6b138a2c29296550b0374c1a5cL39-R41): Downgraded the .NET version from `8.0.303` to `6.0.417` and the `dotnet-ef` tool version from `8.0.0` to `6.0.1`.updated the installation instructions to revert to use dotnet 6 as we have not release the dotnet 8 yet

### CODE REVIEW

**Review by fthorntonai — APPROVED** [review]
Install completed successfully.

**Review by fthorntonai — APPROVED** [review]
Approved

**Review by fthorntonai — APPROVED** [review]
Approved

**Review by fthorntonai — APPROVED** [review]
Reviewed -

**Review by fthorntonai — APPROVED** [review]
Approve Commit

**Review by Jayshaw91 — APPROVED** [review]
Approve

**Comment by santhoshb-msft** [comment]
duplicate of #763

**Pull request closed without merging**
