### PR TITLE
Added automatic redirection when customer is subscribed

### PR DESCRIPTION
**Pull request by k-granados**
This feature allows customers to be automatically redirected to the SaaS App Url once they are subscribed. This fixes issue #181

### CODE REVIEW

**Comment by code4clouds** [comment]
Issue #181

**Comment by code4clouds** [comment]
@neelavarshad  Would you help review this? Thanks

**Review by code4clouds — CHANGES_REQUESTED** [review]
This needs a readme information on how to configure automatic re-direction.

The redirect value should be stored in the config table.

**Comment by neelavarshad** [comment]
@code4clouds Just seeing this. I will update the read-me for making this change

**Comment by santhoshb-msft** [comment]
@neelavarshad please let me know if this satisfies the work item.

**Comment by neelavarshad** [comment]
Looks good. May be closed

**Comment by santhoshb-msft** [comment]
Closing due to conflicts.
@neelavarshad lets get some more details on the requested functionality and rework on this. Hence closing this for now. Unlinked the issue item to keep the item active.

**Pull request closed without merging**
